name: qr_projem
description: Qr Projem

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  google_fonts: ^4.0.1
  flutter_bloc: ^8.1.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_database: ^10.0.15
  firebase_storage: ^11.0.15
  mask_text_input_formatter: ^2.4.0
  flutter_verification_code: ^1.1.6
  uuid: ^3.0.7
  url_launcher: ^6.1.7
  syncfusion_flutter_datepicker: ^20.4.52
  intl: ^0.17.0
  regexed_validator: ^2.0.0+1
  image_picker_web: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/qr/
    - assets/images/contact/
    - assets/images/reference_qrs/
