// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdL2WP6-arlkB4G0gOfVurySSxeWBg76w',
    appId: '1:696026404238:web:0c5a22a80afc0d6eb540df',
    messagingSenderId: '696026404238',
    projectId: 'qrprojem',
    authDomain: 'qrprojem.firebaseapp.com',
    databaseURL: 'https://qrprojem-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrprojem.appspot.com',
    measurementId: 'G-QYKEF0K0PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuZBF5RRvOM42FkKI1PSkFrMMxLeXif0I',
    appId: '1:696026404238:android:7cd1a8f4d4b39e9cb540df',
    messagingSenderId: '696026404238',
    projectId: 'qrprojem',
    databaseURL: 'https://qrprojem-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrprojem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6iGMnf53WKqQooqArC-xZqk5GwvnMAtQ',
    appId: '1:696026404238:ios:9f5a12cf25f0863fb540df',
    messagingSenderId: '696026404238',
    projectId: 'qrprojem',
    databaseURL: 'https://qrprojem-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrprojem.appspot.com',
    iosClientId: '696026404238-5vtft7ho4kk92ivinrudf5kbe6v2enlu.apps.googleusercontent.com',
    iosBundleId: 'demirli.tech.qrProjem',
  );
}
